"""Generate the production secrets Samsoftpay needs on Render.

Run:  python generate_render_secrets.py

It prints copy-paste-ready KEY=VALUE lines and also writes them to
`render_secrets.txt` (git-ignored) so you have a secure local copy.

The app now REFUSES TO BOOT on Render unless SECRET_KEY and
WEBHOOK_SIGNING_SECRET are set to strong, non-default values, so set these
in your Render service Environment before the next deploy.
"""
import secrets
import os

# Set your real admin email here (the first admin login created by /first-setup).
ADMIN_EMAIL = "samsoftware75@gmail.com"


def strong() -> str:
    """A 32-byte URL-safe random token (~256 bits)."""
    return secrets.token_urlsafe(32)


def main() -> None:
    values = {
        "SECRET_KEY": strong(),              # Flask session signing
        "WEBHOOK_SIGNING_SECRET": strong(),  # inbound rail callback HMAC
        "SETUP_TOKEN": strong(),             # gates the one-time /first-setup admin bootstrap
        "ADMIN_EMAIL": ADMIN_EMAIL,          # email for the bootstrap admin account
    }

    lines = [f"{k}={v}" for k, v in values.items()]
    block = "\n".join(lines)

    print("=" * 70)
    print("  SAMSOFTPAY PRODUCTION SECRETS")
    print("  Add each of these in Render -> your web service -> Environment.")
    print("  Add the SAME SECRET_KEY / WEBHOOK_SIGNING_SECRET to the worker")
    print("  and beat services too, so all three share them.")
    print("=" * 70)
    print(block)
    print("=" * 70)
    print("  After deploy, on the Render Shell run ONCE:")
    print("    flask db upgrade            # applies the new migration")
    print("    flask backfill-key-hashes   # hashes existing merchants' API keys")
    print("=" * 70)
    print("  Then bootstrap the admin once (replace <SETUP_TOKEN> with the value above):")
    print("    https://samsoftpay.onrender.com/first-setup?token=<SETUP_TOKEN>")
    print("  It returns a one-time admin password. Save it; it is shown only once.")
    print("=" * 70)

    out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "render_secrets.txt")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# Samsoftpay production secrets - KEEP PRIVATE, do NOT commit.\n")
        f.write("# Generated by generate_render_secrets.py\n\n")
        f.write(block + "\n")
    print(f"  Saved a local copy to: {out_path}")
    print("  KEEP THIS FILE PRIVATE. Do not commit it. Delete after setting on Render.")
    print("=" * 70)


if __name__ == "__main__":
    main()
