"""add role 2fa email fields to merchant

Revision ID: 049cd65af81a
Revises: 9ef3bb747c8b
Create Date: 2026-05-31 10:04:09.588655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '049cd65af81a'
down_revision = '9ef3bb747c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='merchant'))
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('two_fa_enabled', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('otp_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_merchants_role'), ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_role'))
        batch_op.drop_column('otp_expires_at')
        batch_op.drop_column('otp_code')
        batch_op.drop_column('two_fa_enabled')
        batch_op.drop_column('email_verified')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
