"""add logo_filename to merchant

Revision ID: 767dfe8ddef8
Revises: a1745afb7a19
Create Date: 2026-05-31 16:29:48.547557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767dfe8ddef8'
down_revision = 'a1745afb7a19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')

    # ### end Alembic commands ###
