"""add bills and tax configuration tables

Revision ID: 7d73062e7edc
Revises: efbce9790912
Create Date: 2026-05-31 13:25:36.501896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d73062e7edc'
down_revision = 'efbce9790912'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('vat_enabled', sa.Boolean(), nullable=False),
    sa.Column('vat_rate_bps', sa.Integer(), nullable=False),
    sa.Column('vat_number', sa.String(length=50), nullable=True),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('show_levy', sa.Boolean(), nullable=False),
    sa.Column('levy_rate_bps', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('SCHOOL_FEES', 'UTILITY', 'GOVERNMENT', 'HOSPITAL', 'MEMBERSHIP', 'RENT', 'OTHER', name='billcategory'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('account_ref', sa.String(length=120), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=30), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('is_variable', sa.Boolean(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax_rate_bps', sa.Integer(), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_bill_amount_nonneg'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_account_ref'), ['account_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bills_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_bills_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_status'))
        batch_op.drop_index(batch_op.f('ix_bills_public_id'))
        batch_op.drop_index(batch_op.f('ix_bills_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_bills_created_at'))
        batch_op.drop_index(batch_op.f('ix_bills_account_ref'))

    op.drop_table('bills')
    op.drop_table('tax_configurations')
    # ### end Alembic commands ###
