"""add handle to merchant

Revision ID: 97e5ec9d3e89
Revises: 049cd65af81a
Create Date: 2026-05-31 10:31:53.052692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97e5ec9d3e89'
down_revision = '049cd65af81a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handle', sa.String(length=40), nullable=True))
        batch_op.create_index(batch_op.f('ix_merchants_handle'), ['handle'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_handle'))
        batch_op.drop_column('handle')

    # ### end Alembic commands ###
