"""initial schema

Revision ID: 9ef3bb747c8b
Revises: 
Create Date: 2026-05-31 09:37:51.174983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef3bb747c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('public_key', sa.String(length=80), nullable=False),
    sa.Column('secret_key', sa.String(length=80), nullable=False),
    sa.Column('test_public_key', sa.String(length=80), nullable=True),
    sa.Column('test_secret_key', sa.String(length=80), nullable=True),
    sa.Column('webhook_url', sa.String(length=500), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_merchants_public_key'), ['public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchants_secret_key'), ['secret_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchants_test_public_key'), ['test_public_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_merchants_test_secret_key'), ['test_secret_key'], unique=True)

    op.create_table('rail_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rail', sa.Enum('MTN_MOMO', 'AIRTEL_MONEY', 'CARD', name='channel'), nullable=False),
    sa.Column('rail_reference', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rail_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rail_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rail_events_rail_reference'), ['rail_reference'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('RAIL_CLEARING', 'PSP_REVENUE', 'PSP_FLOAT', 'MERCHANT_PENDING', 'MERCHANT_AVAILABLE', 'SUSPENSE', name='accounttype'), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('cached_balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'merchant_id', 'currency', name='uq_account')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=80), nullable=False),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('resource_id', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event'), ['event'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'key', name='uq_idem')
    )
    op.create_table('payout_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('succeeded_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payout_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payout_batches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_batches_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payout_batches_public_id'), ['public_id'], unique=True)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.Enum('MTN_MOMO', 'AIRTEL_MONEY', 'CARD', name='channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'SUCCEEDED', 'FAILED', 'REFUNDED', name='txnstatus'), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('merchant_reference', sa.String(length=120), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=True),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('rail_reference', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_txn_amount_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transactions_rail_reference'), ['rail_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_journal_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_journal_entries_journal_id'), ['journal_id'], unique=False)

    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('success_url', sa.String(length=500), nullable=True),
    sa.Column('cancel_url', sa.String(length=500), nullable=True),
    sa.Column('allow_multiple_uses', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_link_amount_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_links_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_links_public_id'), ['public_id'], unique=True)

    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('channel', sa.Enum('MTN_MOMO', 'AIRTEL_MONEY', 'CARD', name='channel'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AUTHORIZED', 'SUCCEEDED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('recipient_phone', sa.String(length=20), nullable=False),
    sa.Column('recipient_name', sa.String(length=200), nullable=True),
    sa.Column('rail_reference', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_payout_amount_positive'),
    sa.ForeignKeyConstraint(['batch_id'], ['payout_batches.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payouts_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payouts_rail_reference'), ['rail_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_payouts_status'), ['status'], unique=False)

    op.create_table('webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('signature', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_response_code', sa.Integer(), nullable=True),
    sa.Column('last_response_body', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_webhook_deliveries_next_attempt_at'), ['next_attempt_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhook_deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_webhook_deliveries_next_attempt_at'))

    op.drop_table('webhook_deliveries')
    with op.batch_alter_table('payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_payouts_rail_reference'))
        batch_op.drop_index(batch_op.f('ix_payouts_public_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_payouts_created_at'))
        batch_op.drop_index(batch_op.f('ix_payouts_batch_id'))

    op.drop_table('payouts')
    with op.batch_alter_table('payment_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_links_public_id'))
        batch_op.drop_index(batch_op.f('ix_payment_links_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_payment_links_created_at'))

    op.drop_table('payment_links')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_entries_journal_id'))
        batch_op.drop_index(batch_op.f('ix_journal_entries_created_at'))
        batch_op.drop_index('ix_journal_account_created')

    op.drop_table('journal_entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_rail_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_public_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_created_at'))

    op.drop_table('transactions')
    with op.batch_alter_table('payout_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payout_batches_public_id'))
        batch_op.drop_index(batch_op.f('ix_payout_batches_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_payout_batches_created_at'))

    op.drop_table('payout_batches')
    op.drop_table('idempotency_keys')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    op.drop_table('accounts')
    with op.batch_alter_table('rail_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rail_events_rail_reference'))
        batch_op.drop_index(batch_op.f('ix_rail_events_created_at'))

    op.drop_table('rail_events')
    with op.batch_alter_table('merchants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_merchants_test_secret_key'))
        batch_op.drop_index(batch_op.f('ix_merchants_test_public_key'))
        batch_op.drop_index(batch_op.f('ix_merchants_secret_key'))
        batch_op.drop_index(batch_op.f('ix_merchants_public_key'))

    op.drop_table('merchants')
    # ### end Alembic commands ###
