"""add settlement accounts and withdrawal requests

Revision ID: a1745afb7a19
Revises: ada31e3f310a
Create Date: 2026-05-31 16:10:01.064482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1745afb7a19'
down_revision = 'ada31e3f310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlement_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_accounts_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_accounts_public_id'), ['public_id'], unique=True)
        batch_op.create_index('ix_settlement_merchant', ['merchant_id'], unique=False)

    op.create_table('withdrawal_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('settlement_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('fee_amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payout_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_withdrawal_amount_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.ForeignKeyConstraint(['settlement_account_id'], ['settlement_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_status'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_created_at'))

    op.drop_table('withdrawal_requests')
    with op.batch_alter_table('settlement_accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_settlement_merchant')
        batch_op.drop_index(batch_op.f('ix_settlement_accounts_public_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_accounts_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_accounts_created_at'))

    op.drop_table('settlement_accounts')
    # ### end Alembic commands ###
