"""add topup requests table

Revision ID: af632d0cd402
Revises: 767dfe8ddef8
Create Date: 2026-05-31 16:50:20.354279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af632d0cd402'
down_revision = '767dfe8ddef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topup_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_link_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_link_id'], ['payment_links.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topup_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topup_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_topup_requests_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_topup_requests_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_topup_requests_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topup_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topup_requests_status'))
        batch_op.drop_index(batch_op.f('ix_topup_requests_public_id'))
        batch_op.drop_index(batch_op.f('ix_topup_requests_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_topup_requests_created_at'))

    op.drop_table('topup_requests')
    # ### end Alembic commands ###
