"""kyc gift cards subscriptions visa crypto channels

Revision ID: efbce9790912
Revises: 97e5ec9d3e89
Create Date: 2026-05-31 11:01:39.759097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efbce9790912'
down_revision = '97e5ec9d3e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=25), nullable=False),
    sa.Column('face_value', sa.BigInteger(), nullable=False),
    sa.Column('balance', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('redeemed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('face_value > 0', name='ck_giftcard_value_positive'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_cards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gift_cards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_cards_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gift_cards_public_id'), ['public_id'], unique=True)

    op.create_table('kyc_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('tin', sa.String(length=50), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('date_of_incorporation', sa.String(length=20), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=100), nullable=True),
    sa.Column('bank_branch', sa.String(length=100), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=True),
    sa.Column('ownership_structure', sa.String(length=20), nullable=True),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('fatf_country_exposure', sa.Boolean(), nullable=False),
    sa.Column('prior_investigations', sa.Boolean(), nullable=False),
    sa.Column('has_compliance_officer', sa.Boolean(), nullable=False),
    sa.Column('aml_notes', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    with op.batch_alter_table('kyc_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_applications_status'), ['status'], unique=False)

    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.Enum('MTN_MOMO', 'AIRTEL_MONEY', 'CARD', 'VISA', 'CRYPTO', name='channel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscription_plans_public_id'), ['public_id'], unique=True)

    op.create_table('kyc_directors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('city_of_birth', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('id_type', sa.String(length=30), nullable=True),
    sa.Column('id_number', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_directors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_directors_application_id'), ['application_id'], unique=False)

    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['kyc_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_documents_application_id'), ['application_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=40), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_email', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('next_billing_at', sa.DateTime(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_next_billing_at'), ['next_billing_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_public_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_next_billing_at'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_created_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_documents_application_id'))

    op.drop_table('kyc_documents')
    with op.batch_alter_table('kyc_directors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_directors_application_id'))

    op.drop_table('kyc_directors')
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_public_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_subscription_plans_created_at'))

    op.drop_table('subscription_plans')
    with op.batch_alter_table('kyc_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_applications_status'))

    op.drop_table('kyc_applications')
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_cards_public_id'))
        batch_op.drop_index(batch_op.f('ix_gift_cards_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_gift_cards_created_at'))
        batch_op.drop_index(batch_op.f('ix_gift_cards_code'))

    op.drop_table('gift_cards')
    # ### end Alembic commands ###
